# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: craftland.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'craftland.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63raftland.proto\x12\tcraftland\"\x8a\x01\n\x11\x43raftlandSlotInfo\x12\x0f\n\x07slot_id\x18\x01 \x01(\r\x12\x12\n\nslot_state\x18\x02 \x01(\r\x12\x15\n\rworkshop_code\x18\x03 \x01(\t\x12\x39\n\x13workshop_basic_info\x18\x04 \x01(\x0b\x32\x1c.craftland.WorkshopBasicInfo\"\x9d\x04\n\x11WorkshopBasicInfo\x12\x15\n\rworkshop_name\x18\x01 \x01(\t\x12\x11\n\tauthor_id\x18\x02 \x01(\t\x12\x11\n\tperf_cost\x18\x03 \x01(\t\x12\x13\n\x0bupdate_time\x18\x04 \x01(\x04\x12\x1b\n\x13resource_statistics\x18\x05 \x01(\t\x12\x13\n\x0b\x61uthor_name\x18\x06 \x01(\t\x12\x15\n\rworkshop_desc\x18\x07 \x01(\t\x12\x11\n\tgame_mode\x18\x08 \x01(\r\x12\x0c\n\x04tags\x18\t \x03(\r\x12\x15\n\rmode_settings\x18\n \x01(\t\x12\x12\n\nteam_count\x18\x0b \x01(\r\x12\x19\n\x11mini_map_settings\x18\x0c \x01(\t\x12 \n\x18mini_map_object_settings\x18\r \x01(\t\x12\x0e\n\x06map_id\x18\x0e \x01(\r\x12\x13\n\x0b\x63reate_time\x18\x0f \x01(\x04\x12\x43\n\x0c\x63omment_info\x18\x10 \x03(\x0b\x32-.craftland.WorkshopBasicInfo.CommentInfoEntry\x12\x18\n\x10mode_template_id\x18\x11 \x01(\r\x12\x12\n\nob_version\x18\x12 \x01(\r\x12\x18\n\x10matchmaking_rule\x18\x13 \x01(\t\x1a\x32\n\x10\x43ommentInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"u\n\x14\x43raftlandAccountInfo\x12\x0b\n\x03\x65xp\x18\x01 \x01(\r\x12\x14\n\x0c\x63reate_times\x18\x02 \x01(\r\x12\x12\n\nauthor_tag\x18\x03 \x01(\r\x12\x12\n\nlike_count\x18\x04 \x01(\r\x12\x12\n\nplay_count\x18\x05 \x01(\r\")\n\x13\x43raftlandProfileReq\x12\x12\n\naccount_id\x18\x01 \x01(\x04\"\x98\x01\n\x13\x43raftlandProfileRes\x12\x37\n\x11\x61uthor_slots_info\x18\x01 \x03(\x0b\x32\x1c.craftland.CraftlandSlotInfo\x12\x35\n\x0c\x61\x63\x63ount_info\x18\x02 \x01(\x0b\x32\x1f.craftland.CraftlandAccountInfo\x12\x11\n\tauthor_id\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'craftland_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKSHOPBASICINFO_COMMENTINFOENTRY']._loaded_options = None
  _globals['_WORKSHOPBASICINFO_COMMENTINFOENTRY']._serialized_options = b'8\001'
  _globals['_CRAFTLANDSLOTINFO']._serialized_start=31
  _globals['_CRAFTLANDSLOTINFO']._serialized_end=169
  _globals['_WORKSHOPBASICINFO']._serialized_start=172
  _globals['_WORKSHOPBASICINFO']._serialized_end=713
  _globals['_WORKSHOPBASICINFO_COMMENTINFOENTRY']._serialized_start=663
  _globals['_WORKSHOPBASICINFO_COMMENTINFOENTRY']._serialized_end=713
  _globals['_CRAFTLANDACCOUNTINFO']._serialized_start=715
  _globals['_CRAFTLANDACCOUNTINFO']._serialized_end=832
  _globals['_CRAFTLANDPROFILEREQ']._serialized_start=834
  _globals['_CRAFTLANDPROFILEREQ']._serialized_end=875
  _globals['_CRAFTLANDPROFILERES']._serialized_start=878
  _globals['_CRAFTLANDPROFILERES']._serialized_end=1030
# @@protoc_insertion_point(module_scope)
