# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workshop_author.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'workshop_author.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15workshop_author.proto\x12\x08workshop\"C\n\x12WorkshopAuthorInfo\x12\x0c\n\x04maps\x18\x01 \x03(\t\x12\x12\n\nbasic_info\x18\x03 \x01(\x0c\x12\x0b\n\x03uid\x18\x04 \x01(\x04\"\xf4\x01\n\x0f\x41uthorBasicInfo\x12\x11\n\tauthor_id\x18\x01 \x01(\x04\x12\x13\n\x0b\x61uthor_name\x18\x02 \x01(\t\x12\x11\n\tavatar_id\x18\x03 \x01(\r\x12\x11\n\tbanner_id\x18\x04 \x01(\r\x12\x15\n\rdesigns_count\x18\x05 \x01(\r\x12\x13\n\x0blikes_count\x18\x06 \x01(\x04\x12\x1b\n\x13subscriptions_count\x18\x07 \x01(\x04\x12\x0c\n\x04rank\x18\x08 \x01(\r\x12\x13\n\x0btotal_plays\x18\t \x01(\x04\x12\x13\n\x0btotal_likes\x18\n \x01(\x04\x12\x12\n\ntotal_maps\x18\x0b \x01(\r\"\xbd\x01\n\x07MapInfo\x12\x10\n\x08map_code\x18\x01 \x01(\t\x12\x10\n\x08map_name\x18\x02 \x01(\t\x12\x10\n\x08map_type\x18\x03 \x01(\r\x12\r\n\x05plays\x18\x04 \x01(\x04\x12\r\n\x05likes\x18\x05 \x01(\x04\x12\x11\n\tgame_mode\x18\x06 \x01(\r\x12\x13\n\x0b\x63reate_time\x18\x07 \x01(\x04\x12\x13\n\x0bupdate_time\x18\x08 \x01(\x04\x12\x13\n\x0b\x64\x65scription\x18\t \x01(\t\x12\x0c\n\x04tags\x18\n \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workshop_author_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKSHOPAUTHORINFO']._serialized_start=35
  _globals['_WORKSHOPAUTHORINFO']._serialized_end=102
  _globals['_AUTHORBASICINFO']._serialized_start=105
  _globals['_AUTHORBASICINFO']._serialized_end=349
  _globals['_MAPINFO']._serialized_start=352
  _globals['_MAPINFO']._serialized_end=541
# @@protoc_insertion_point(module_scope)
